[workspace]

[package]
# Pseudo-package whose dependencies are imported and buckified
name = "rust-third-party"
version = "0.0.0"
edition = "2021"
publish = false

# Dummy target to keep Cargo happy
[[bin]]
name = "top"
path = "top/main.rs"

# List of packages to be imported, with version constraints, features
# and all options Cargo supports.
[dependencies]
anyhow = "1.0.97"
async-std = "1.12"
async-trait = "0.1.86"
axum = "0.8.1"
bitflags = "2.9.0"
bytes = "1.10.1"
caps = "0.5.5"
chrono = { version = "0.4", default-features = false, features = [
    "clock",
    "serde",
] }
clap = { version = "4.5.32", features = ["derive"] }
cni-plugin = "0.2.1"
env_logger = "0.11.7"
errno = { version = "0.3.10", optional = true }
fastrand = "^2.3.0"
fixedbitset = "0.5.7"
fuse3 = { version = "0.8.1", features = ["tokio-runtime", "unprivileged"] }
futures = "0.3.31"
futures-util = "0.3.31"
hex = "0.4.3"
http-body = "0.4.5"
hyper = "0.14.27"
libbpf-sys = { version = "1.5.0", optional = true }
libc = "0.2.171"
liboci-cli = "0.5.1"
libseccomp = "0.3.0"
log = "0.4.26"
macaddr = "1.0.1"
nc = "0.9.5"
netlink-packet-route = "0.22.0"
nix = { version = "0.29.0", features = [
    "signal",
    "user",
    "fs",
    "socket",
    "sched",
    "mount",
    "mman",
    "resource",
    "dir",
    "term",
    "hostname",
] }
oci-spec = { version = "~0.7.1", features = ["runtime"] }
once_cell = "1.21.2"
openssl = { version = "0.10.71", features = ["vendored"] }
prctl = "1.0.0"
procfs = "0.17.0"
prost = "0.13.5"
prost-types = "0.12.6"
protobuf = "=3.2.0"
radix_trie = "0.2.1"
rand = "0.9.0"
rbpf = { version = "0.3.0", optional = true }
regex = { version = "1.10.6", default-features = false, features = [
    "std",
    "unicode-perl",
] }
reqwest = { version = "0.12.7", features = ["json", "blocking"] }
rtnetlink =  "0.16.0"
rust-criu = "0.4.0"
safe-path = "0.1.0"
semver = "0.11.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.138"
serde_yaml = "0.9"
sha2 = "0.10.8"
thiserror = "2.0.12"
tokio = { version = "1.44.0", features = ["full"] }
tokio-util = { version = "0.7.13", features = ["io"] }
tonic = "0.13"
tracing = { version = "0.1.41", features = ["attributes"] }
tracing-journald = "0.3.1"
tracing-subscriber = { version = "0.3.19", features = ["json", "env-filter"] }
uuid = { version = "1.15.1", features = [
    "v4",
    "fast-rng",
    "macro-diagnostics",
] }
vm-memory = "0.16.1"
vmm-sys-util = "0.12.1"

# Local patches - typically git references
[patch.crates-io]
