on:
  pull_request:
    paths-ignore:
      - '.github/**'
      - 'docs/**'
      - 'project/libcgroups/**'
      - 'project/libcontainer/**'
      - 'project/tools/**'

name: Base Workflow for Check, Build and Tests

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  setup:
    strategy:
      fail-fast: false

    name: Setup and cache
    runs-on: ubuntu-latest

    env:
      CARGO_TERM_COLOR: always

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Rust Toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy rustfmt

  format:
    name: Rustfmt Check
    runs-on: ubuntu-latest
    needs: setup

    env:
      CARGO_TERM_COLOR: always

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      
      - name: Run rustfmt
        run: |
          cd project
          cargo fmt --all --check

  clippy:
    name: Clippy Check
    strategy:
      fail-fast: true

    runs-on: ubuntu-latest
    needs: setup
    env:
      CARGO_TERM_COLOR: always

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install system dependencies
        uses: ./.github/install-sys-deps

      - name: Run cargo clippy
        run: |
          cd project
          cargo clippy --workspace -- -D warnings

  build:
    name: Buck2 Build

    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install system dependencies
        uses: ./.github/install-sys-deps

      - name: Build with Buck2
        run: |
          reindeer --third-party-dir third-party vendor
          reindeer --third-party-dir third-party buckify
          buck2 build //project/...

      - name: Cache buck-out
        uses: actions/cache/save@v4
        with:
          path: ./buck-out
          key: buck2-cache-${{ github.run_id }}-${{ github.run_attempt }}

  test:
    name: Buck2 Test

    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install system dependencies
        uses: ./.github/install-sys-deps

      - name: Run tests with Buck2
        run: echo "Running tests with Buck2 ..."